apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: todo-dotnet-promote-to-prod
spec:
  params:
    - default: 'https://github.com/sgnus-infra/todo-dotnet-application.git'
      description: Git repository of source code
      name: SOURCE_CODE_GIT_REPO
      type: string
    - name: TAG_NAME
      type: string
      description: "The promoted tag name"
    - default: 'https://github.com/sgnus-infra/todo-application-infra.git'
      description: Git repository of infra code repo
      name: INFRA_GIT_REPO
      type: string
    - default: main
      description: Git ref of infra code repo
      name: INFRA_GIT_REF
      type: string
    - default: quay-registry-quay-quay-enterprise.apps.dev.ocp.nus.edu.sg/devops/todo-dotnet
      description: Image
      name: IMAGE
      type: string
    - default: deploy/app-dotnet/overlays/prod/dep-todo-prod.yaml
      description: Path to deployment manifest
      name: MANIFEST_FILE
      type: string
    - default: latest
      description: Version
      name: VERSION
      type: string
  tasks:
    - name: update-manifest
      params:
        - name: insecure-skip-tls-verify
          value: 'true'
        - name: gitRepositoryUrl
          value: $(params.INFRA_GIT_REPO)
        - name: gitRepositoryRevision
          value: $(params.INFRA_GIT_REF)
        - name: pushToRevision
          value: ''
        - name: manifestFile
          value: $(params.MANIFEST_FILE)
        - name: image
          value: $(params.IMAGE)
        - name: imageTagName
          value: $(params.TAG_NAME)
      taskRef:
        name: update-manifest
      workspaces:
        - name: infra-repo
          workspace: infra-repo
    - name: acs-deployment-check
      params:
        - name: rox_api_token
          value: stackrox
        - name: rox_central_endpoint
          value: stackrox
        - name: insecure-skip-tls-verify
          value: "true"
        - name: gitRepositoryUrl
          value: $(params.INFRA_GIT_REPO)
        - name: gitRepositoryRevision
          value: $(params.INFRA_GIT_REF)``
        - name: skipPull
          value: "false"
        - name: appName
          value: app-dotnet
      runAfter:
        - update-manifest
      taskRef:
        name: acs-deployment-check
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: push-manifest
      params:
        - name: insecure-skip-tls-verify
          value: 'true'
        - name: gitRepositoryUrl
          value: $(params.INFRA_GIT_REPO)
        - name: gitRepositoryRevision
          value: $(params.INFRA_GIT_REF)
        - name: pushToRevision
          value: $(params.INFRA_GIT_REF)
      runAfter:
        - acs-deployment-check
      taskRef:
        name: push-manifest
      workspaces:
        - name: infra-repo
          workspace: infra-repo
  workspaces:
    - description: >
        This workspace contains source code, so they can be read by the next
        task.
      name: shared-workspace
    - name: infra-repo
      description: | 
        This workspace contains all infra manifests.
