kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-dotnet-app
  labels:
    app: todo-dotnet-app
    app.kubernetes.io/component: todo-dotnet-app
    app.kubernetes.io/instance: todo-dotnet-app
    app.kubernetes.io/name: todo-dotnet-app
    app.kubernetes.io/part-of: todo-dotnet-app
    app.openshift.io/runtime: dotnet
    app.openshift.io/runtime-version: 7.0-ubi8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-dotnet-app
  template:
    metadata:
      labels:
        app: todo-dotnet-app
        deployment: todo-dotnet-app
    spec:
      imagePullSecrets:
        - name: devops-baby-pull-secret
      containers:
        - name: todo-dotnet-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/todo-app/todo-dotnet-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600