kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: todo-dotnet-route
  labels:
    app: todo-dotnet-app
    app.kubernetes.io/component: todo-dotnet-app
    app.kubernetes.io/instance: todo-dotnet-app
    app.kubernetes.io/name: todo-dotnet-app
    app.kubernetes.io/part-of: todo-dotnet-app
    app.openshift.io/runtime: dotnet
    app.openshift.io/runtime-version: 7.0-ubi8
spec:
  to:
    kind: Service
    name: todo-dotnet-svc
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None