kind: Service
apiVersion: v1
metadata:
  name: todo-dotnet-svc
  labels:
    app: todo-dotnet-app
    app.kubernetes.io/component: todo-dotnet-app
    app.kubernetes.io/instance: todo-dotnet-app
    app.kubernetes.io/name: todo-dotnet-app
    app.kubernetes.io/part-of: todo-dotnet-app
    app.openshift.io/runtime: dotnet
    app.openshift.io/runtime-version: 7.0-ubi8
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: todo-dotnet-app
    deployment: todo-dotnet-app