apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: todo-java-build-and-push
spec:
  params:
    - name: SOURCE_CODE_GIT_REPO
      type: string
      default: "https://github.com/secangkirkopipanas/todo-application.git"
      description: "Git repository of source code"
    - name: SOURCE_CODE_GIT_REF
      type: string
      default: main
      description: "Git ref of source code repo"
    - name: INFRA_GIT_REPO
      type: string
      default: "https://github.com/secangkirkopipanas/todo-application-infra.git"
      description: "Git repository of infra code"
    - name: INFRA_GIT_REF
      type: string
      default: main
      description: "Git ref of infra code repo"
    - name: IMAGE
      type: string
      default: quay-registry-quay-quay-enterprise.apps.dev.ocp.nus.edu.sg/devops/todo-java
      description: "Image name for application"
    - name: GIT_COMMIT_ID
      type: string
      description: "Last Git commit ID"
  workspaces:
    - name: shared-workspace
      description: | 
        This workspace contains source code, so they can be read by the next task.
    - name: maven-local-repo
      description: | 
        This workspace contains all Maven dependencies used by the application.
    - name: infra-repo
      description: | 
        This workspace contains all infra manifests.
    - name: dockerconfig
      description: | 
        This workspace contains docker config.
    - name: github-basic-auth
  tasks:
    - name: fetch-source
      params:
      - name: url
        value: $(params.SOURCE_CODE_GIT_REPO)
      - name: revision
        value: $(params.SOURCE_CODE_GIT_REF)
      - name: deleteExisting
        value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-workspace
      - name: basic-auth
        workspace: github-basic-auth
    - name: build
      taskRef:
        name: maven
      runAfter:
        - fetch-source
      params:
        - name: OPENJDK_IMAGE
          value: registry.access.redhat.com/ubi9/openjdk-17:1.16
        - name: GOALS
          value: "clean package checkstyle:check"
        - name: SKIP_TESTS
          value: "true"          
        - name: MAVEN_OPTS
          value: ""
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-local-repo
          workspace: maven-local-repo
    - name: build-image-and-push
      taskRef:
        name: s2i-java
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-local-repo
          workspace: maven-local-repo
        - name: infra-repo
          workspace: infra-repo
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: GIT_COMMIT_ID
          value: $(params.GIT_COMMIT_ID)
        - name: TLSVERIFY
          value: "false"
        - name: VERSION
          value: latest
    - name: acs-image-scan
      taskRef:
        name: acs-image-scan
      runAfter:
        - build-image-and-push
      params:
        - name: rox_api_token
          value: stackrox
        - name: rox_central_endpoint
          value: stackrox
        - name: insecure-skip-tls-verify
          value: "true"
        - name: image
          value: $(params.IMAGE)
        - name: git_commit_id
          value: $(params.GIT_COMMIT_ID)
    - name: acs-image-check
      params:
        - name: rox_central_endpoint
          value: stackrox
        - name: rox_api_token
          value: stackrox
        - name: image
          value: $(params.IMAGE)
        - name: insecure-skip-tls-verify
          value: 'true'
        - name: git_commit_id
          value: $(params.GIT_COMMIT_ID)
      runAfter:
        - acs-image-scan
      taskRef:
        kind: Task
        name: acs-image-check
    - name: update-manifest-and-push
      taskRef:
        name: update-manifest
      runAfter:
        - acs-image-check
      params:
        - name: insecure-skip-tls-verify
          value: "true"
        - name: gitRepositoryUrl
          value: $(params.INFRA_GIT_REPO)
        - name: gitRepositoryRevision
          value: $(params.INFRA_GIT_REF)
        - name: pushToRevision
          value: "$(params.INFRA_GIT_REF)"
        - name: manifestFile
          value: deploy/app-java/overlays/dev/dep-todo.yaml
        - name: image
          value: $(params.IMAGE)
        - name: imageTagName
          value: "$(params.GIT_COMMIT_ID)"
      workspaces:
        - name: infra-repo
          workspace: infra-repo