apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo-java-dev-applicationset
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-todo-java'
    spec:
      destination:
        name: ''
        namespace: todo-dev
        server: '{{url}}'
      source:
        path: deploy/app-java/overlays/dev
        repoURL: https://github.com/sgnus-infra/todo-application-infra
        targetRevision: HEAD
      sources: []
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
