apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-dotnet
spec:
  destination:
    name: ''
    namespace: todo-dev
    server: https://kubernetes.default.svc
  source:
    path: pipeline/dotnet
    repoURL: https://github.com/secangkirkopipanas/todo-application-infra.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
