apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dotnet-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: todo-dotnet-app
          image: >-
            quay.io/rh_rh/todo-dotnet:168ed8039a
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
