apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-sit
resources:
  - ../../base

patches:
  - path: dep-todo.yaml
  - path: dep-todo-db.yaml
  - path: sealed-secrets-todo.yaml
  
configMapGenerator:
  - name: todo-java-configmap
    literals:
      - timezone="Asia/Singapore"
      - java_options="-Xms512M -Xmx1G"
      - spring_active_profiles="sit"
      - h2_console_enabled="false"
      - datasource_driver_classname="org.postgresql.Driver"
      - datasource_url="jdbc:postgresql://todo-java-db-svc:5432/todo-java-sit-db"
      - jpa_dialect="org.hibernate.dialect.PostgreSQLDialect"
  - name: todo-java-db-configmap
    literals:
      - timezone="Asia/Singapore"
      - database_name="todo-java-sit-db"