---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
  namespace: todo-sit
spec:
  encryptedData:
    database-password: AgBKYnzJQz0rFdgz4uUlT32tUx8sTzjmHNERMtZ461QyhHxGMZPxKDDGDnYB5A7zKVXTkGqvHGui2mpeigq4DPB9ler54TxX+eUW+xCLNE8LUXGjKp5LxLnGKqvtdt1XcAWYP2IpA66fJqNWSj/k2LBu4hMmVCEc3W5C5Is1c4QOB1wopaDHUbULMJDIEJApD5qPv+QqaraKBPXC+B3IOGYfNmn4IhVh7wri7SBHFDGUO8WVZH9LbQ3tUWLMD210OPSjLDIufn7uvj0gtgbVM/Pc29PrZW4IALcON+v22tu9p3crRhuGBP5EMItJnCYBRnw4rQk6q3bkGRixjPy8KnnTfiLtV+6RICsa9QXKtAC34Rgw3/c0asjwoLy8eSlcy2AOVba5Nk99nGALdR/dN2NGnPtRoVR+jZPsr45R0i29l2cC63RQ7Q4ZxropcMu9NJn1x+Mgn1qO7gnrFCgSFPqjK+xwe2IormjoN8ZjjR8Ml46HtvFUw7cE/peyARFNQ2tcBKfH6aBx+w2rqMmidSsHl7+vZd4haqg2N5ALCwiVFd9kLzpb0mEWZLI8YsRE5gbIGcr3Vj2AQlATGlqEcPfw5kQOmk80DcUd6LpLSyW6GzOIkq++181ht3pmEw2GKq6UbK7hTtblEdtAD/Ldx2L54cY5aj/GTCN2SqZfXiiU2+ZYLcxVz4plxqT3DVMoVR/+mx5+4Z7Z3RDO
    database-user: AgA6FGISAKGTtTxEhQS3p61ONElkKZkHAi+mgcDym2Qc3QPpgBIAVYrDi86TYpF4zA3jpethM9QKKeEoGFkwSGDRlsDR9PeuBQz1AnfLyPoKw5VbOyhyuhfAlxumaUUE15BEMZK2g5CWeUbYIFLzyWgO2NXinghv8ElkXYi/Ro1XQYYhfFj0mWEcRc9TGf3dgolQ2eLHuhuvaL8ILGA/aQj15sIW14bnhnATSENISo38Zh1RG8cZALQLEZ7HaDDyru4CX5WnMo8RNl/swzqWrdU2vKhCdnuGob1Nc4HpSI1oDAiEfnYXqKzYicH7IZoRuKAsR85K2n1LVG6GlOhNNz+BF1ABptFsu7FpNVt73VpnZt/te+czIO7pYGyRTbf7zO8Cqwf95LRJblIz63AWrt6CcL8WO9t2mEFa6yaI9PdqjzY2k23f/1UQKIhKEN4C+dX+QdIvFLjvlgiwbHBg8W/nqyTnh2Kth8WtLyuTJyclwVp1R3hNhhXuDEBMEY+2yU0WxQFfxMNyXdKRmz/OEIBXNEnAIoB96XhC95BM/vYsVS/MH/oRt9aBW8V2NZJSaD1RW0B3Wex3T6GpbCeRRBQvzPnoz4sdmGxKMhKK/ZBa8y5GDGvTQIvK/rrfFPuScTg7v1qzOVuyqWaiAQoy47YJ1OcRDzRn6Tlempnk3v6Ixll1DCKL3mHNvglT4QxzQ6/dX03USCit
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
      namespace: todo-sit
    type: Opaque
