---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-java-db-secret
  namespace: todo-sit
spec:
  encryptedData:
    database-password: AgBiXq/cF9shnocMT3v/i1CFOWAN2PJgzw1gqczBA45gufb5drvpl452OVF6NeRDGqDGMhcqeRvKL1S39w56ZTBejpdTi9L8K0Obe7R31Nfxa03z8mQ9cqn+VlwVzM+aTnXgcZsapAx8FGMgHTuhuBZC4+hsGaunVlrB1rDaoaC7uJHItv2mAMRM6h8U1dL5TMkfG46iAIjRgnCTQutP24dP9uO+LIpEwI+86s4v7Jp95QSK6+tfnUVewlyKFuuai6KvqEiZZcRs4D6sV7TYe3LJFyokGhJ4ByhYTM6qjfmecSfK17TSsExOCE2dbMdFLuTDIvSm+83zopfpgmvSe0+ojs6TmxfKg+iLmLx4bUerF2sv1V+ZqGYXmc4RuSkQjzbAdelgOsOatnGvfEAoppcSFirC0OgSS/DalH9CMbFKENOAi8xvA2qMXui+2FG6e9kQ8QnnDOOXiPp/OMm1GY5zWhBtWIAIv+jb+h+WcUKf6YLuHdkk7WGHYtjlu2JTyFwekepTFfzIPgK6KhVOeuvecA5C5pDyw8+vHHU2ctfzuKRjM26SdtvFU0qUprrZl8EeXLNg2DGudNGllcuRJSgKbY7tqae4+rG6rtYlqumpiMeNaBDYbUh88FZhzIqb4ZL4VptOWUlJwbr2EtRR1T3OARNbTnfAadZcDQwIZw/quu6iDeMt6iZovIhRwA+t8vio3FT4uEExK4m0
    database-user: AgCweIjH0xPyUCRVrhzSuLsciTT6lJHirM5RvihCokDl43cRXxpj8XZ/IahIPLzKb/2Jc1eJVeF/90Qt6gWNsLNWXuRead79WvGI6o9TbS6ad7q5aMZFee8eRI6PL6Taf2ym5d3FFWm5r24lB0uehL6xeWFbYbTUbZxxnK7BtvPje5qR8MipkSj3D39CrG6fJalTPjHruAYnjowt0Yqa60RCKb8z/h0YjSx2Yn43A1TMOgr7MUf+XxIRSbDJ25pVCebbvfbwNrF2itrPrGzO0vCB2IFRViZKDT6b/wzCdDI3w4PukO77UuuK0rFKBS7DD7uEKyCr5xybUkLq1uQNE+bKbA5WcFzg5uSgoQj5IOB64gVsp2+DFwlC9f7kGQVxaHBhCx9UHlvjruYkt8exBb4JF3+e3bR2GdHXrM+ufBKQ7bgwo5NviREMGGnr9OLuVHJiy0Yg+SOUOl/Z11yBqyp/hqvqR6Ehu0n1AnRyDr8lbaS1b16os2yNF24xNyiHDgT4rQyCowDUggVmueg9p9dhveaYvoShvtCH//SHP23ZQ+xAM0Y3+M+lwQ9QT3SQpWoMzfEXct8dB8gvJfWSZPxfwKdC2IkApWy0pVy3v/gxPzOwp+akgQUM5/jr2MCvQppU+Bs2HXCvsNIL6YdOEjFWX1fScPSMNtletzOMRUJLn7XooOLda6uOChhoTZgnRARcQFonN10a
  template:
    metadata:
      creationTimestamp: null
      name: todo-java-db-secret
      namespace: todo-sit
    type: Opaque
